services:
  mysql:
    image: docker.io/mysql:8.4.6
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ldocker
    ports:
      - "3307:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-uroot", "-p${DB_PASSWORD}" ]
      interval: 30s
      timeout: 10s
      retries: 3
  #redis
  redis:
    image: docker.io/redis:7.4-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ldocker
    # пароль для Redis
    command: redis-server
      --requirepass ${REDIS_PASSWORD:-secret}
      --appendonly yes
      --appendfsync everysec
      --save 300 1
      --save 60 5
      --save 10 100
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${REDIS_PASSWORD:-secret}", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 3

  rabbitmq:
    image: docker.io/rabbitmq:4.0-management
    container_name: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-admin}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-secret}
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - ldocker
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "check_port_connectivity" ]
      interval: 30s
      timeout: 10s
      retries: 3


  nginx:
    image: docker.io/nginx:1.29.2
    container_name: nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx.local.conf:/etc/nginx/conf.d/nginx.local.conf
#     - ./docker/nginx/nginx.prod.conf:/etc/nginx/conf.d/nginx.prod.conf
      - ./backend:/var/www/html
    networks:
      - ldocker

  laravel:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel
    environment:
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_HOST:  ${REDIS_HOST:-redis}
      REDIS_PASSWORD: ${REDIS_PASSWORD:-secret}
      REDIS_PORT: ${REDIS_PORT:-6379}
      RABBITMQ_HOST: ${RABBITMQ_HOST:-rabbitmq}
      RABBITMQ_PORT: ${RABBITMQ_PORT:-5672}
      RABBITMQ_USER: ${RABBITMQ_USER:-admin}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD:-secret}
      RABBITMQ_VHOST: /
    volumes:
      - ./backend:/var/www/html
    restart: always
    networks:
      - ldocker
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "php", "artisan", "env" ]
      interval: 30s
      timeout: 10s
      retries: 3

  phpmyadmin:
    image: docker.io/phpmyadmin:5.2.3
    container_name: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      - UPLOAD_LIMIT=2G
      - PMA_HOST=${DB_HOST}
      - PMA_PORT=${DB_PORT}
      - PMA_USER=${DB_USERNAME}
      - PMA_PASSWORD=${DB_PASSWORD}
    networks:
      - ldocker

  nuxtjs:
    image: docker.io/node:24.10.0
    container_name: lesson-docker.nuxtjs
    restart: always
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    networks:
      - ldocker
    command: sh -c "npm install && npm run dev"

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local
  rabbitmq_data:
    driver: local

networks:
  ldocker:
    driver: bridge
